# Generated by Django 4.1.7 on 2023-03-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='electionresult',
            constraint=models.UniqueConstraint(condition=models.Q(('ballot_box__isnull', False), ('candidate__isnull', False)), fields=('candidate', 'ballot_box'), name='election_electionresult_conditional_unique_candidate_ballot_box'),
        ),
    ]
