# Generated by Django 4.1.7 on 2023-03-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_electionresult_election_electionresult_conditional_unique_candidate_ballot_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballotbox',
            name='box_number',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='Box Number'),
        ),
    ]
