# Generated by Django 4.1.7 on 2023-03-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_alter_ballotbox_box_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='end_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='election',
            name='start_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Start Date'),
        ),
    ]
