# Generated by Django 4.1.7 on 2023-03-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_alter_election_end_date_alter_election_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='election',
            options={'ordering': ('-start_date',), 'verbose_name': 'Election', 'verbose_name_plural': 'Elections'},
        ),
        migrations.AlterModelOptions(
            name='electioncandidate',
            options={'ordering': ('-election__start_date', 'name'), 'verbose_name': 'Election Candidate', 'verbose_name_plural': 'Election Candidates'},
        ),
        migrations.AlterField(
            model_name='ballotbox',
            name='box_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Box Number'),
        ),
        migrations.AddConstraint(
            model_name='ballotbox',
            constraint=models.UniqueConstraint(condition=models.Q(('election__isnull', False)), fields=('election', 'box_number'), name='election_ballotbox_conditional_unique_election_box_number'),
        ),
    ]
