# Generated by Django 4.1.7 on 2023-03-30 03:10

from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'fixtures/cities_fixture.json')


def unload_fixture(apps, schema_editor):
    "Brutally deleting all entries for this model..."
    models = [
        'city',
        'citytranslation',
        'town',
        'towntranslation',
        'district',
        'districttranslation',
    ]
    for model_name in models:
        model = apps.get_model("tools", model_name)
        model.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('election', '0005_alter_election_options_and_more'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]
