# Generated by Django 4.1.7 on 2023-03-30 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0007_election_fixture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ballotbox',
            options={'ordering': ('-election__start_date', 'election__translations__name', 'box_number'), 'verbose_name': 'Ballot Box', 'verbose_name_plural': 'Ballot Boxes'},
        ),
        migrations.AlterModelOptions(
            name='ballotboxreport',
            options={'ordering': ('-ballot_box__election__start_date', 'ballot_box__election__translations__name', '-created_date'), 'verbose_name': 'Ballot Box Report', 'verbose_name_plural': 'Ballot Box Reports'},
        ),
        migrations.AlterModelOptions(
            name='electionresult',
            options={'ordering': ('-ballot_box__election__start_date', 'ballot_box__election__translations__name', 'ballot_box__box_number', 'candidate__name'), 'verbose_name': 'Election Result', 'verbose_name_plural': 'Election Results'},
        ),
    ]
