# Generated by Django 4.1.7 on 2023-03-26 22:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('first_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, default=None, max_length=255, null=True, verbose_name='Email')),
                ('phone_extension', models.CharField(default='+90', max_length=6, verbose_name='Phone extension')),
                ('phone', models.CharField(blank=True, default=None, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d{7,15}$')], verbose_name='Phone')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ('-created_date',),
            },
        ),
    ]
