# Generated by Django 4.1.7 on 2023-03-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('user__isnull', False), ('first_name__isnull', True), ('last_name__isnull', True), ('email__isnull', True), ('phone__isnull', True)), models.Q(('user__isnull', True), ('first_name__isnull', False), ('last_name__isnull', False), ('email__isnull', False), ('phone__isnull', False)), _connector='OR'), name='only_one_of_user_or_email_first_name_last_name_phone_can_be_set'),
        ),
    ]
