# Generated by Django 4.1.7 on 2023-03-27 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_alter_socialmedia_options'),
        ('user', '0002_gdprconsent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gdprconsent',
            options={'ordering': ('-created_date',), 'verbose_name': 'GDPR Consent', 'verbose_name_plural': 'GDPR Consents'},
        ),
        migrations.CreateModel(
            name='UserAuthorizedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('district', models.ManyToManyField(blank=True, default=None, to='tools.district', verbose_name='District')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_authorized_area', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Authorized Area',
                'verbose_name_plural': 'User Authorized Areas',
                'ordering': ('-created_date',),
            },
        ),
    ]
