# Generated by Django 4.1.7 on 2023-03-26 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'ordering': ('order',), 'verbose_name': 'Social Media', 'verbose_name_plural': 'Social Media Links'},
        ),
    ]
