# Generated by Django 4.1.7 on 2023-03-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_alter_socialmedia_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='Postal code'),
        ),
    ]
